### ISSUE TITLE
Readme完善

### ISSUE THREAD

**Issue by abstiger** [xiajunyi/smallbus#9]
Star+1，Readme需要完善一下！

**Comment by xiajunyi** [comment]
感谢强哥的提醒，已更新[README](https://github.com/xiajunyi/smallbus/blob/master/README.md)

**Comment by dkvirus** [comment]
@xiajunyi 赞👍，背景第一行貌似有个错别字哈：【公共号】=>【公众号】。

**Comment by xiajunyi** [comment]
@dkvirus 修改过了，好眼力！
